### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by infloop** [lidofinance/validator-ejector#35]
Please add more logs on each job run:
* last exited validator index from consensus
* last validator index sent to consensus
* last validator index from event (execution)
* network (and chain id)
* node operator id (and name)
* number of messages in messages folder
* number of events that are not processed

**Comment by Eddort** [comment]
- [x] last exited validator index from consensus
- [x] last validator index sent to consensus
- [x]  last validator index from event (execution)
- [ ] network (and chain id)
- [ ] node operator id (and name)
- [x] number of messages in messages folder
- [ ] number of events that are not processed 
https://github.com/lidofinance/validator-ejector/pull/36
