### ISSUE TITLE
load more messages dynamically

### ISSUE THREAD

**Issue by rfunduk** [lidofinance/validator-ejector#55]
it seems like the messagesProcessor only loads messages on startup

https://github.com/lidofinance/validator-ejector/blob/566b5c5dc254567c3984bf52851c12000454ea3b/src/app/service.ts#L25

since the job processor [also has the message processor](https://github.com/lidofinance/validator-ejector/blob/develop/src/services/job-processor/service.ts#L30) available, it would be nice if it could just call `.load()` to pick up any new messages added since the last run

as it stands, as far as i can tell, i have to restart the ejector every time i load in fresh messages

(edit. i suppose it should also verify the messages!)

**Comment by kolyasapphire** [comment]
Thanks for the feedback!

That's correct. Currently, an app restart is required for the Ejector to pick up new exit messages, unfortunately.

We have this feature in our backlog, will implement it as soon as urgent tasks are finished.

Will leave the issue open so you know when it's done.

**Comment by infloop** [comment]
This is implemented and merged in PR https://github.com/lidofinance/validator-ejector/pull/99. Please use the latest released version.
