### ISSUE TITLE
Recommendation regarding the validator_ejector_exit_messages metric

### ISSUE THREAD

**Issue by PacoBits** [lidofinance/validator-ejector#75]
We believe it is necessary to differentiate between pre-signed messages with errors and pre-signed messages from exited validators.

Currently, both an incorrect pre-signed message and a pre-signed message from an exited validator are treated equally, incrementing the value of the metric: `validator_ejector_exit_messages{valid="false", app="validator-ejector"} 3`

It might be appropriate to introduce another metric for pre-signed messages with formatting errors:
`validator_ejector_exit_messages_on_error`
or alternatively, not to consider messages from exited validators as errors

**Comment by kolyasapphire** [comment]
Hey @PacoBits

We are going to treat exit messages for exited validators as valid in the next version.

It turns out this behaviour was necessary for calculating how many exit messages are left. Since we are reworking that logic anyway (for #74), we are correcting this as well.

**Comment by kolyasapphire** [comment]
Done in `sha256:2dc26e26ea3ac487ddde0bae29ca3e2cbb5052aef267309c2c87a6ec2ac8fd23`
